apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: bacl
        image: docker.io/darylmcbride/todolist
        ports:
        - containerPort: 8181
        env:
        - name: MYSQL_IP
          value: mysql
